// Daftar kota/kabupaten besar Indonesia untuk combobox checkout.
// Disengaja dibundel (bukan fetch remote) agar instan + tetap jalan di
// koneksi lemah. Pembeli tetap boleh ketik manual bila kotanya tak ada.

export const CITIES: string[] = [
  "Ambon",
  "Balikpapan",
  "Banda Aceh",
  "Bandar Lampung",
  "Bandung",
  "Bandung Barat",
  "Banjarmasin",
  "Banjarnegara",
  "Bantul",
  "Banyumas",
  "Banyuwangi",
  "Batam",
  "Batu",
  "Bekasi",
  "Bengkulu",
  "Binjai",
  "Bitung",
  "Blitar",
  "Bogor",
  "Bojonegoro",
  "Bondowoso",
  "Boyolali",
  "Brebes",
  "Bukittinggi",
  "Cianjur",
  "Cilegon",
  "Cimahi",
  "Cirebon",
  "Demak",
  "Denpasar",
  "Depok",
  "Dumai",
  "Garut",
  "Gianyar",
  "Gorontalo",
  "Gresik",
  "Indramayu",
  "Jakarta Barat",
  "Jakarta Pusat",
  "Jakarta Selatan",
  "Jakarta Timur",
  "Jakarta Utara",
  "Jambi",
  "Jayapura",
  "Jember",
  "Jombang",
  "Karawang",
  "Kebumen",
  "Kediri",
  "Kendal",
  "Kendari",
  "Kepulauan Seribu",
  "Klaten",
  "Kudus",
  "Kupang",
  "Lamongan",
  "Langsa",
  "Lhokseumawe",
  "Lumajang",
  "Madiun",
  "Magelang",
  "Makassar",
  "Malang",
  "Mamuju",
  "Manado",
  "Mataram",
  "Medan",
  "Metro",
  "Mojokerto",
  "Padang",
  "Padang Panjang",
  "Palangka Raya",
  "Palembang",
  "Palu",
  "Pangkal Pinang",
  "Parepare",
  "Pasuruan",
  "Payakumbuh",
  "Pekalongan",
  "Pekanbaru",
  "Pematang Siantar",
  "Pontianak",
  "Probolinggo",
  "Purwakarta",
  "Purwokerto",
  "Sabang",
  "Salatiga",
  "Samarinda",
  "Sampang",
  "Semarang",
  "Serang",
  "Sibolga",
  "Sidoarjo",
  "Singkawang",
  "Sleman",
  "Solo",
  "Sorong",
  "Subang",
  "Sukabumi",
  "Sumedang",
  "Surabaya",
  "Surakarta",
  "Tangerang",
  "Tangerang Selatan",
  "Tanjung Balai",
  "Tanjung Pinang",
  "Tarakan",
  "Tasikmalaya",
  "Tebing Tinggi",
  "Tegal",
  "Temanggung",
  "Ternate",
  "Tidore Kepulauan",
  "Tomohon",
  "Tulungagung",
  "Yogyakarta",
];

export function searchCities(q: string, limit = 8): string[] {
  const needle = q.trim().toLowerCase();
  if (!needle) return CITIES.slice(0, limit);
  return CITIES.filter((c) => c.toLowerCase().includes(needle)).slice(0, limit);
}
